# build stage
FROM node:lts-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# สร้างอิมเมจ Docker ของแอป Vue.js
# docker build -t vuejs-cookbook/dockerize-vuejs-app .
# เรียกใช้แอป Vue.js ของเราในคอนเทนเนอร์ Docker
# docker run -it -p 8080:80 --rm --name dockerize-vuejs-app-1 vuejs-cookbook/dockerize-vuejs-app


