name: Dependency Review

on:
  pull_request:
    branches: [main, develop2, refactor-dev, review-code]

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
